name: Build (pr)

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Install dependencies
      run: dotnet restore
    - id: make_version_string
      uses: sandersaares-actions/make-time-based-version-string@main
      with:
        buildType: pr
    - id: make_nuget_version_string
      uses: sandersaares-actions/make-time-based-nuget-version-string@main
      with:
        versionstring: ${{ steps.make_version_string.outputs.VERSION_STRING }}
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal --filter Name\\!~_WindowsOnly
    - name: Package
      run: dotnet pack --configuration Release --no-restore --include-source -p:PackageVersion="${{ steps.make_nuget_version_string.outputs.NUGET_VERSION_STRING }}"
    - uses: actions/upload-artifact@v2
      with:
        name: nupkg
        path: '**/*.nupkg'